apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-unsealer.fullname" . }}
  namespace: {{ include "vault-unsealer.namespace" . }}
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}

spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vault-unsealer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vault-unsealer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vault-unsealer.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: vault-unsealer
          configMap:
            name: vault-unsealer
            defaultMode: 0777
            items:
              - key: vault-unsealer.sh
                path: vault-unsealer.sh
        - name: vault-init
          secret:
            secretName: vault-init
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
          args:
            - -c
            - /scripts/vault-unsealer.sh
          env:
            - name: NAMESPACE
              value: {{ include "vault-unsealer.namespace" . | quote }}
            - name: VAULT_RELEASE_NAME
              value: {{ .Values.vaultReleaseName | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: vault-unsealer
              mountPath: /scripts/vault-unsealer.sh
              subPath: vault-unsealer.sh
            - name: vault-init
              mountPath: /secrets
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
